name: Build and deploy Python app to Azure Web App - RedScore

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Prepare deployment directory
        run: |
          mkdir -p deploy
          rsync -av --exclude=deploy --exclude=venv --exclude=.git . ./

      - name: Debug deployment directory
        run: ls -R ./

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Debug downloaded files
        run: ls -R ./

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'RedScore'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BB346165292C40EEACBC3FF46123CC16 }}
          package: ./
